---
title: "One model and several risk classes"
output:
  html_document:
    df_print: paged
---

```{r}
library(latex2exp)
library(kableExtra)
library(ggplot2)
library(dplyr)
library(tidyr)
library(rstudioapi)
library(IsoPriceR)
library(readr)
library(xtable)
setwd(dirname(getActiveDocumentContext()$path))
getwd()

calculate_age <- function(birthdate) {
  # Parse the birthdate
  birth_date <- as.Date(birthdate, format = "%d/%m/%Y")
  
  # Get the current date
  current_date <- Sys.Date()
  
  # Calculate the difference in years
  years <- as.numeric(format(current_date, "%Y")) - as.numeric(format(birth_date, "%Y"))
  
  # Adjust for birthdate not yet reached this year
  if (format(current_date, "%m%d") < format(birth_date, "%m%d")) {
    years <- years - 1
  }
  # Calculate the difference in months
  months <- as.numeric(format(current_date, "%m")) - as.numeric(format(birth_date, "%m"))
  
  # Adjust if birth month hasn't been reached this year
  if (months < 0) {
    months <- months + 12
  }
  
  # Create the age string
  if(years >0 ){
    age_string <- paste(years, "years")
  }else{
    age_string <- paste(months, "months")
  }
  return(age_string)
}

pet_insurance_FR_multiple_risk_class <- read_delim("../data/pet_insurance_FR_multiple_risk_class.csv", 
                                                   delim = ";", escape_double = FALSE, trim_ws = TRUE) 
pet_insurance_FR_multiple_risk_class$age <- sapply(pet_insurance_FR_multiple_risk_class$birthdate, function(birthdate) calculate_age(birthdate))

pet_insurance_FR_multiple_risk_class <- pet_insurance_FR_multiple_risk_class %>% mutate(x = commercialPremium,
  key_risk_class = paste(specie, breed, gender, age)) %>% select(-c(birthdate, commercialPremium)) %>% filter(age != "6 years")
# Distributor 5 does not discriminate with the age of the dog and distributor 1 does not differentiate betwen 4 months and 2 years
pet_insurance_FR_multiple_risk_class <- rbind(pet_insurance_FR_multiple_risk_class,
  pet_insurance_FR_multiple_risk_class %>% filter(insurance_carrier == 5) %>% mutate(age = "2 years")  %>% mutate(key_risk_class = paste(specie, breed, gender, age)),
  pet_insurance_FR_multiple_risk_class %>% filter(insurance_carrier == 5) %>% mutate(age = "4 years") %>% mutate(key_risk_class = paste(specie, breed, gender, age)),
  pet_insurance_FR_multiple_risk_class %>% filter(insurance_carrier == 1 & breed == "golden-retriever" & age == "4 months") %>% mutate(age = "2 years") %>% mutate(key_risk_class = paste(specie, breed, gender, age)))
  
pet_insurance_FR_multiple_risk_class  <- pet_insurance_FR_multiple_risk_class %>% arrange(specie, gender, breed, substr(age,3,3), substr(age,1,1))
addmargins(table(pet_insurance_FR_multiple_risk_class$key_risk_class , pet_insurance_FR_multiple_risk_class$insurance_carrier))
risk_classes_df <- pet_insurance_FR_multiple_risk_class %>%
  distinct(specie, breed, gender, age) %>%
  arrange(specie, gender, breed, substr(age,3,3), substr(age,1,1))

latex_code <- xtable(risk_classes_df)
print(latex_code)
```
# Premium specification

```{r}
p_p <- pure_premium("xs", c("r", "d", "l"))
```

# Loss Model

We simply consider the 

$$
\text{Poisson}(\lambda) - \text{LogNormal}(\mu, \sigma = 1)
$$

```{r}
lnorm_dist <- model("lognormal", c("mu", "sigma"))
pois_dist <- model("poisson", c("lambda"))
l_m <- loss_model(pois_dist, lnorm_dist, "Pois(lambda)-Lognormal(mu,sigma=1)")
```

# Prior assumptions

```{r}
prior_mu <- prior_dist("uniform", "mu",c(-10, 10))
prior_sigma_c <- prior_dist("constant", "sigma", c(1))
prior_lambda <- prior_dist("uniform", "lambda", c(0, 10))
prior_distribution <- independent_priors(list(prior_lambda, prior_mu, prior_sigma_c))
```



```{r}
# data <- data %>% filter(race == "australian sheperd")
popSize <- 1000;  MC_R<- 2000; acc <- 1; sp_bounds <- c(0.4, 0.7); set.seed(1234)
risk_classes <- unique(pet_insurance_FR_multiple_risk_class$key_risk_class)
res_abc_risk_classes <- list()
k <- 0
for(risk_class in risk_classes){
  k <- k + 1
  print(risk_class)
  data <- pet_insurance_FR_multiple_risk_class[pet_insurance_FR_multiple_risk_class$key_risk_class == risk_class, ]
  res_abc <- abc(data, prior_distribution, l_m, p_p, popSize, MC_R, acc, sp_bounds)
  res_abc_risk_classes[[k]] <- res_abc
}
names(res_abc_risk_classes) <- risk_classes
save(res_abc_risk_classes, file = "../data/res_abc_risk_classes.RData")


# c("r","d", "l", "x")
# #  Unparallel
# system.time(res_abc_list <- lapply(1:n_models, function(k) abc(data, prior_distributions[[k]], loss_models[[k]], p_p, popSize, MC_R, acc, sp_bounds)))
# save(res_abc_list, file = "../data/res_abc_real_data.RData")
# # Going Paralell

```


# Posterior analysis
```{r}
risk_class = risk_classes[1]
metric_df <- data.frame()
pp_df <-  data.frame()
for(risk_class in risk_classes){
  res_abc <- res_abc_risk_classes[[risk_class]]
  last_cloud <- extract_last_cloud(res_abc)
  # posterior_plots(last_cloud, prior_distribution, l_m, ref_line = FALSE, font_size = 20 )
  data <- pet_insurance_FR_multiple_risk_class[pet_insurance_FR_multiple_risk_class$key_risk_class == risk_class, ]
  last_cloud_df <- as.data.frame(last_cloud)
  res_metric <- compute_metric_cloud(data, p_p, l_m, last_cloud)
  pp_df <- rbind(pp_df,
    data.frame(cps =data$x,
      pps = apply(res_metric$pps, MARGIN =1, FUN = mean),
      risk_class = risk_class, insurance_carrier = data$insurance_carrier)
    )
  metric_df <- rbind(metric_df, data.frame(lambda = last_cloud_df$lambda, 
                                     mu = last_cloud_df$mu,
                                     Claim_Frequency = res_metric$estimates$Claim_Frequency,
                                     Claim_Amount = res_metric$estimates$Claim_Amount,
                                     Prob_0 = res_metric$estimates$Prob_0,
                                     Total_Claim_Amount = res_metric$estimates$Total_Claim_Amount,
                                     LR = res_metric$estimates$LR, 
                                     risk_class = risk_class))
}
```

```{r}
risk_classes_df <- risk_classes_df %>% mutate(risk_class = paste(specie, breed, gender, age))
metric_df_V1 <- metric_df %>% left_join(risk_classes_df, by = 'risk_class') %>%
  arrange(specie, gender, breed, substr(age,3,3), substr(age,1,1)) %>% mutate(age = factor(age, levels = c("4 months", "2 years", "4 years"))) 

# boxplot of the claim frequency parameter 
boxplot_lambda <- ggplot(data = metric_df_V1) + geom_boxplot(mapping = aes(y = lambda, x = breed, color = as.factor(age))) + 
  theme_classic(base_size = 20)+ 
  labs(x= "Breed",  title = TeX("\\lambda"), y = "", color = "Age") +  
     theme(axis.text.x = element_text(size = 12, angle = 45, vjust = 0.6))
ggsave(paste0("../figures/boxplot_lambda_multiple_risk_classes.pdf"), boxplot_lambda)

# boxplot of the claim severity parameter 
boxplot_mu <- ggplot(data = metric_df_V1) + geom_boxplot(mapping = aes(y = mu, x = breed, color = as.factor(age))) + 
  theme_classic(base_size = 20)+ 
  labs(x= "Breed",  title = TeX("\\mu"), y = "", color = "Age") +  
     theme(axis.text.x = element_text(size = 12, angle = 45, vjust = 0.6))
ggsave(paste0("../figures/boxplot_mu_multiple_risk_classes.pdf"), boxplot_mu)

# boxplot of the Claim_Frequency
ggplot(data = metric_df_V1) +  geom_boxplot(mapping = aes(y = Claim_Frequency, x = breed, color = as.factor(age))) + 
  theme_classic(base_size = 20)+ 
  labs(x= "Breed",  title = TeX("E(N)"), y = "", color = "Age") +  
     theme(axis.text.x = element_text(size = 12, angle = 45, vjust = 0.6))

# boxplot of the Claim_Amount
ggplot(data = metric_df_V1) +  geom_boxplot(mapping = aes(y = Claim_Amount, x = breed, color = as.factor(age))) + 
  theme_classic(base_size = 20)+ 
  labs(x= "Breed",  title = TeX("E(U)"), y = "", color = "Age") +  
     theme(axis.text.x = element_text(size = 12, angle = 45, vjust = 0.6))

# boxplot of P(N=0)
ggplot(data = metric_df_V1) +  geom_boxplot(mapping = aes(y = Prob_0, x = breed, color = as.factor(age))) + 
  theme_classic(base_size = 20)+ 
  labs(x= "Breed",  title = TeX("P(N=0)"), y = "", color = "Age") +  
     theme(axis.text.x = element_text(size = 12, angle = 45, vjust = 0.6))

# boxplot of the total claim amounts 
boxplot_EX <- ggplot(data = metric_df_V1) +  geom_boxplot(mapping = aes(y = Total_Claim_Amount, x = breed, color = as.factor(age))) + 
  theme_classic(base_size = 20)+ 
  labs(x= "Breed",  title = TeX("E(X)"), y = "", color = "Age") +  
     theme(axis.text.x = element_text(size = 12, angle = 45, vjust = 0.6))
ggsave(paste0("../figures/boxplot_EX_multiple_risk_classes.pdf"), boxplot_EX)

# boxplot of the LR
boxplot_LR <- ggplot(data = metric_df_V1) +  geom_boxplot(mapping = aes(y = LR, x = breed, color = as.factor(age))) + 
  theme_classic(base_size = 20)+ 
  labs(x= "Breed",  title = TeX("LR"), y = "", color = "Age") +  
     theme(axis.text.x = element_text(size = 12, angle = 45, vjust = 0.6))
ggsave(paste0("../figures/boxplot_LR_multiple_risk_classes.pdf"), boxplot_LR)
```
```{r}
pp_df_V1 <- pp_df %>% left_join(risk_classes_df, by = 'risk_class') %>%
  arrange(specie, gender, breed, substr(age,3,3), substr(age,1,1)) %>% mutate(age = factor(age, levels = c("4 months", "2 years", "4 years"))) 

# boxplot of the claim frequency parameter 
ggplot(data = pp_df_V1 %>% filter(breed == "german sheperd" & age == "2 years") ) + geom_point(mapping = aes(y = cps, x = pps, color = as.factor(insurance_carrier))) + 
  theme_classic(base_size = 20)+ 
  labs(x= "Pure Premium", y = "Commercial Premium", color = "Insurance carrier") +  
     theme(axis.text.x = element_text(size = 12, angle = 45, vjust = 0.6))

```


## Posterior distribution of the model parameters
```{r}
load("../data/res_abc_real_data.RData")
k <- 1

for(k in 1:n_models){
  last_cloud <- extract_last_cloud(res_abc_list[[k]])
  posterior_plots(last_cloud, prior_distributions[[k]], loss_models[[k]], ref_line = FALSE, font_size = 20 )
  # best_cloud <- extract_best_cloud(res_abc_list[[k]])
  # posterior_plots(best_cloud, prior_distributions[[k]], loss_models[[k]], ref_line = FALSE, font_size = 20 )
  ggsave(paste0("../figures/post_plot_",loss_models[[k]]$model_name, ".pdf"))
  
}

tab <- data.frame( model = sapply(1:n_models, function(k) loss_models[[k]]$model_name),
            eps = sapply(1:n_models, function(k) max(res_abc_list[[k]]$ds[[length(res_abc_list[[k]]$ds)]]))
            )
print(xtable(tab[order(tab$eps) ,]), include.rownames=FALSE)

# posterior_plots(best_cloud, prior_distributions[[k]], loss_models[[k]], ref_line = FALSE, font_size = 20 )
```

## Point estimate of key quantities

```{r}
posterior_point_estimates <- data.frame()
for(k in 1:length(res_abc_list)){
  # bp <- t(as.matrix(extract_best_particle(res_abc_list[[k]])))
  mode <- t(as.matrix(extract_mode(res_abc_list[[k]], loss_models[[k]], prior_distributions[[k]])))
  map <- t(as.matrix(colMeans(extract_last_cloud(res_abc_list[[k]]))))
  df <- rbind(compute_metric_particle(data, p_p, loss_models[[k]], map, method = "map")$estimates,
      compute_metric_particle(data, p_p, loss_models[[k]], mode, method = "mode")$estimates
      )
  posterior_point_estimates <- rbind(posterior_point_estimates, df)
}
```
### MAP and mode for each model

```{r}
tab <- posterior_point_estimates %>% filter(parm_names == "mu"| parm_names == "alpha"| parm_names == "sigma" | parm_names == "lambda"| parm_names == "p")%>% pivot_wider(names_from = c(method), values_from = parm_values)
print(xtable(tab), include.rownames=FALSE)
```


### Claim frequency and severity

```{r}
tab <- posterior_point_estimates %>% filter(parm_names == "Claim_Frequency" | parm_names == "Prob_0" | parm_names == "Claim_Amount") %>% pivot_wider(names_from = c(method,parm_names), values_from = parm_values) %>% select("model", "map_Prob_0", "mode_Prob_0", "map_Claim_Frequency", "mode_Claim_Frequency", "map_Claim_Amount", "mode_Claim_Amount")
print(xtable(tab), include.rownames=FALSE)
```

### Total Claim amount 

```{r}
tab <- posterior_point_estimates %>% filter(parm_names == "Total_Claim_Amount" | parm_names == "LR") %>% pivot_wider(names_from = c(method,parm_names), values_from = parm_values) %>% select("model", "map_LR", "mode_LR", "map_Total_Claim_Amount", "mode_Total_Claim_Amount")
print(xtable(tab), include.rownames=FALSE)
```



## Posterior predictive distribution

```{r}

posterior_predictive_distribution <- data.frame()
for(k in 1:length(res_abc_list)){
  last_cloud <- extract_last_cloud(res_abc_list[[k]])
  posterior_estimates <- compute_metric_cloud(data, p_p, loss_models[[k]], last_cloud)$estimates  
  posterior_predictive_distribution <- rbind(posterior_predictive_distribution, posterior_estimates)  
}
unique(posterior_predictive_distribution$model)

```

```{r}
library(latex2exp)
TeX(r'($Bin(a=12,p)-Gam(\alpha,\beta=1)$)')
quantity <- colnames(posterior_predictive_distribution)[2:6][1]
quantity_titles <- c("Claim Frequency", "Claim Amount", "P(N=0)", "Total Claim Amount","Loss Ratio" )
x_ticks <- c(TeX(r'($Bin(a=12,p)-Gam(\alpha,\beta=1)$)'), 
             TeX(r'($Bin(a=12,p)-LNorm(\mu,\sigma=1)$)'),
             TeX(r'($Bin(a=12,p)-LNorm(\mu=0,\sigma)$)'), 
             TeX(r'($Geom(p)-Gam(\alpha,\beta=1)$)'),
             TeX(r'($Geom(p)-LNorm(\mu,\sigma=1)$)'),
             TeX(r'($Geom(p)-LNorm(\mu=0,\sigma)$)'),
             TeX(r'($Pois(\lambda)-Gam(\alpha,\beta=1)$)'),
             TeX(r'($Pois(\lambda)-LNorm(\mu,\sigma=1)$)'),
             TeX(r'($Pois(\lambda)-LNorm(\mu=0,\sigma)$)'))
i <- 1
for(quantity in colnames(posterior_predictive_distribution)[2:6]){
  (post_boxplot <- ggplot(data = posterior_predictive_distribution) + 
     geom_boxplot(mapping = aes(x = eval(parse(text=quantity)) , y = as.factor(model))) + 
     theme_classic(base_size = 20)+ labs(x= "",  title = quantity_titles[i], y = "") +  
     scale_y_discrete(labels= x_ticks) +
     theme(axis.text.x = element_text(size = 16)))
  i <- i+1
  ggsave(paste0("../figures/post_boxplot_real_data_",quantity, ".pdf"), post_boxplot)
}
```

### f a posteriori

```{r}
iso_df <- data.frame()
k <- 1

for(k in 1:length(res_abc_list)){
  map <- t(as.matrix(colMeans(extract_last_cloud(res_abc_list[[k]]))))
  pp <- compute_metric_particle(data, p_p, loss_models[[k]], map, method = "map")$pp
  # mode <- t(as.matrix(extract_mode(res_abc_list[[k]], loss_models[[k]], prior_distributions[[k]])))
  # pp <- compute_metric_particle(data, p_p, loss_models[[k]], mode, method = "mode")$pp
  res_iso <- isoreg(pp, data$x)
  iso_df <- rbind(iso_df,
                data.frame(model = rep(loss_models[[k]]$model_name, nrow(data)), x= sort(res_iso$x), y = res_iso$yf))
}

(iso_plot <- ggplot(data = iso_df) + geom_step(mapping = aes(x= x, y = y, color = model)) +  ggplot2::theme_classic(base_size = 14) + labs(x= "Pure premium", y = "Commercial premium", title = "", color = "Model") + theme(legend.position="none")) 

ggsave("../figures/iso_real_data_all_models.pdf", iso_plot)
```

## Focus on the Poisson-Lognormal(mu=0, sigma)

```{r}
loss_model_names <- sapply(1:9, function(k) loss_models[[k]]$model_name)
k <- 1
posterior_predictive_distribution %>% filter(model == loss_model_names[k])
res_abc_pois_lnorm_sigma1 <- res_abc_list[[k]]
last_cloud <- extract_last_cloud(res_abc_list[[k]])
map <- t(as.matrix(colMeans(last_cloud)))
pp_pois_lnorm_sigma1 <- compute_metric_particle(data, p_p, loss_models[[k]], map)$pp 
data["pp"] <- pp_pois_lnorm_sigma1
res_iso <- isoreg(pp_pois_lnorm_sigma1, data$x)
iso_df <-data.frame(model = rep(loss_models[[k]]$model_name, nrow(data)), x= sort(res_iso$x), y = res_iso$yf)

(ggplot() + geom_point(data = data, mapping = aes(x = pp, y = x, color = as.factor(carrier))) + geom_step(data = iso_df, mapping = aes(x = x, y = y)) + labs(x= "Pure Premium", y = "Commercial premium", title = "", color = "") + ggplot2::theme_classic(base_size = 20) + theme(legend.position = "none")) 
ggsave("../figures/iso_pois_lnorm_sigma1.pdf")
```


