---
title: "Plots of section 2, section 3 and Appendix A of Market-Based Insurance Ratemaking"
output: html_notebook
---


```{r}
knitr::opts_chunk$set(echo = TRUE)
library(latex2exp)
library(IsoPriceR)
library(ggplot2)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
getwd()
```
# Section 2
## Figure 1

```{r}

set.seed(142)

# Loss model
freq_dist <- model("poisson", c("lambda"))
sev_dist <- model("lognormal", c("mu", "sigma"))
l_m <- loss_model(freq_dist, sev_dist, "Poisson-Lognormal")

# True parameter
lambda_true <- 3; mu_true <- 0; sigma_true <- 1
true_parms <- t(as.matrix(c(lambda_true, mu_true, sigma_true)))
colnames(true_parms) <- l_m$parm_names

# Data
## Sample of claim data to calculate the true pure premium via Monte Carlo
X_true <- sample_X(l_m, true_parms, R = 10000)

## Characteristics of the pure premium which depends on the parameter of the insurance coverage
p_p <- pure_premium("xs", c("r", "d", "l"))
## Random premium parameters
n <- 100; d <- runif(n, min = 0, max =  6); r <- runif(n, min = 0.5, max =  1); l <- rep(Inf, n)

## Data frame with the insurance coverage parameters and the pure premium
th_premium <- matrix(c(r, d, l), nrow = n)
pps <- compute_pure_premia(X_true, coverage_type = "xs", th_premium)
df_pp <- data.frame(r = r, d = d, l = l, pp=pps)

## Scatter plot of pure premium as a function of the deductibe and depending on the rate of coverage
(pp_plot <- ggplot(data = df_pp) + geom_point(mapping = aes(x= d, y = pp, size = r)) + labs(x= "d", y = "Pure premium", title = "") + ggplot2::theme_classic(base_size = 20) )
ggsave("../figures/pp_plot.pdf", pp_plot)
```
## Figure 2

```{r}
# Random safety loading
eta <- runif(n, 1.5, 3)

#Calculation of the commercial premium
df_pp["cp_linear"] <- eta * df_pp$pp
data <- df_pp[c("r", "d", "l")]
data["x"] <- df_pp$cp

# Scatter plot of comercial premium as a function of the pure premium
(cp_plot <- ggplot(data = df_pp) + geom_point(mapping = aes(x= pp, y = cp_linear))  + labs(x= "Pure premium", y = "Commercial premium", title = "") + ggplot2::theme_classic(base_size = 20) )
ggsave("../figures/cp_plot.pdf", cp_plot)
```
# Section 3
## Figure 3

```{r}
# Isotonic fit of commercial premium explained by pure premium
res_iso <- isoreg(df_pp$pp, df_pp$cp_linear)
df_pp <- df_pp[order(df_pp$pp), ]
df_pp["cp_iso_linear"] <- res_iso$yf

# Visualization of the isotonic fit
(iso_plot <- ggplot(data = df_pp) + geom_point(mapping = aes(x= pp, y = cp_linear)) + geom_step(mapping = aes(x= pp, y = cp_iso_linear)) +  ggplot2::theme_classic(base_size = 20) + labs(x= "Pure premium", y = "Commercial premium", title = "")) 
ggsave("../figures/iso_plot.pdf", iso_plot)
```
## Figure 4

```{r}
data <- df_pp[,c("r", "d", "l")]
data["x"] <- df_pp$pp
ths_premium <- as.matrix(data[p_p$parm_names])
lambda_true <- 3; mu_true <- 0; sigma_true <- 1

# Pure premium calculation for a range of risk model parameters
lambdas<- seq(0.5, 5, 0.1); sigmas <- seq(0.1, 2, 0.1)
cloud <- as.matrix(expand.grid(lambdas, c(0),sigmas))
colnames(cloud) <- l_m$parm_names
X <- sample_X(l_m , cloud, R = 10000)
pp_fake <- compute_pure_premia(X, coverage_type = "xs", ths_premium)
                                                                     
# Calculation of the RMSE between true and wrong pure premium
ds <- sapply(1:nrow(cloud), function(k) mean((pp_fake[, k] - data$x)^2)^(1/2)) 
df_ds <- data.frame(cloud)
df_ds <- cbind(df_ds, ds)

# Generate custom contour levels
min_ds <- min(df_ds$ds); max_ds <- max(df_ds$ds)
breaks <- seq(min_ds, 1.5, length.out = 10)  # 5 levels from min_ds to 10
breaks <- round(c(breaks, seq(1.5, max(df_ds$ds), length.out = 2)) *100) / 100  # 10 levels from 10 to max_ds

(pp_contour_plot <- ggplot(df_ds, aes(x = lambda, y = sigma, z = ds)) + 
  geom_contour_filled(breaks = breaks) + 
  labs(x = TeX("$\\lambda$"), y = TeX("$\\sigma$"), fill = "RMSE") + ggplot2::theme_classic(base_size = 20) + ggplot2::theme(legend.position="right"))
ggsave(paste0("../figures/pp_contour_plot.pdf"), pp_contour_plot)
```
## Figure 5 a)

```{r}
data["x"] <- df_pp$cp_linear
cps <- data$x

# Isotonic fit of the commercial premium associated to the wrong pure preium
ress_iso <- lapply(1:ncol(pp_fake), function(k) isoreg(pp_fake[, k], cps))
fs <- lapply(ress_iso, function(res_iso) stepfun(sort(res_iso$x), c(min(res_iso$yf) /2 ,
                                                                      res_iso$yf), f = 1))
ds <- sapply(1:nrow(cloud), function(k) mean((fs[[k]](pp_fake[, k]) - data$x)^2)^(1/2)) 

df_ds <- data.frame(cloud)
df_ds <- cbind(df_ds, ds)
min_ds <- min(df_ds$ds)

# Generate custom contour levels
breaks <- seq(min_ds, 1, length.out = 10)  # 5 levels from min_ds to 10
breaks <- round(c(breaks, seq(1, max(df_ds$ds), length.out = 2)) *100) / 100  # 10 levels from 10 to max_ds

(cp_contour_plot_wo_rg <- ggplot(df_ds, aes(x = lambda, y = sigma, z = ds)) + 
  geom_contour_filled(breaks = breaks) +
  labs(x = TeX("$\\lambda$"), y = TeX("$\\sigma$"), fill = TeX("$\\epsilon$")) + ggplot2::theme_classic(base_size = 20) + ggplot2::theme(legend.position="right"))
ggsave(paste0("../figures/cp_contour_plot_wo_rg.pdf"), cp_contour_plot_wo_rg)

```

## Figure 5 b)

```{r}
# Adding the regukarization terms
sp_bounds <- c(min(df_pp$pp / df_pp$cp_linear), max(df_pp$pp / df_pp$cp_linear))  
ds1 <- sapply(1:ncol(pp_fake), function(k) sqrt(mean((pmax(cps - pp_fake[,k] /sp_bounds[1], 0) )^2)))
ds2 <- sapply(1:ncol(pp_fake), function(k) sqrt(mean((pmax( pp_fake[,k] / sp_bounds[2] - cps , 0) )^2)))
ds <- ds + ds1 + ds2
df_ds <- data.frame(cloud)
df_ds <- cbind(df_ds, ds)

# Generate custom contour levels
breaks <- seq(min_ds, 3.5, length.out = 10)  # 5 levels from min_ds to 10
breaks <- round(c(breaks, seq(3.5, max(df_ds$ds), length.out = 2)) *100) / 100  # 10 levels from 10 to max_ds

(cp_contour_plot_w_rg <- ggplot(df_ds, aes(x = lambda, y = sigma, z = ds)) + 
  geom_contour_filled(breaks = breaks) +
  labs(x = TeX("$\\lambda$"), y = TeX("$\\sigma$"), fill = TeX("$\\epsilon$")) + ggplot2::theme_classic(base_size = 20) + ggplot2::theme(legend.position="right"))
ggsave(paste0("../figures/cp_contour_plot_w_rg.pdf"), cp_contour_plot_w_rg)
```

# Figure 6

```{r}

# Prior settings for the parameters
prior_lambda <- prior_dist("uniform", "lambda",c(0, 10))
prior_mu <- prior_dist("constant", "mu",c(0))
prior_sigma <- prior_dist("uniform", "sigma", c(0, 5))
prior_distributions <- list(prior_lambda, prior_mu, prior_sigma)
model_prior <- independent_priors(prior_distributions)

# Settings for the abc algorithm
popSize <- 1000;  MC_R<- 1000; acc <- 0.1; sp_bounds <- c(0.3, 0.66)
data <- df_pp[,c("r", "d", "l")]
data["x"] <- df_pp$cp_linear
res_abc <- abc(data, model_prior, l_m, p_p, popSize, MC_R, acc, sp_bounds)
```
```{r}
# We retrieve the cloud of particles associated to each generation
cloud_dfs <- lapply(res_abc$Clouds, as.data.frame)
cloud_df <- do.call(rbind, cloud_dfs)
cloud_df$generation <- sort(rep(1:length(res_abc$Clouds), popSize))
cloud_df_plot <- rbind(
  data.frame(parm = cloud_df$lambda, parm_name = "lambda", generation = cloud_df$generation),
  data.frame(parm = cloud_df$sigma, parm_name = "sigma", generation = cloud_df$generation)
)
cloud_df_plot$parm_name <-as.factor(cloud_df_plot$parm_name) 
levels(cloud_df_plot$parm_name) <- c(lambda = TeX("$\\lambda$"), sigma = TeX("$\\sigma$"))
```

### Figure 6 a)

```{r}
abc_gen_post_lambda <- ggplot2::ggplot(data = cloud_df ) + ggplot2::geom_density(data = cloud_df, mapping = aes(x=lambda, color = as.factor(generation))) + ggplot2::labs(x=TeX("$\\lambda$"), y = "Density", color = "Generation") + ggplot2::theme_classic(base_size = 20) + ggplot2::theme(legend.position="right") + ggplot2::geom_vline(ggplot2::aes(xintercept=true_parms[,1]), color="black",
                                   linetype="dashed")
ggsave(paste0("../figures/abc_gen_post_lambda.pdf"), abc_gen_post_lambda)
```

### Figure 6 b)

```{r}
abc_gen_post_sigma <- ggplot2::ggplot(data = cloud_df ) + ggplot2::geom_density(data = cloud_df, mapping = aes(x=sigma, color = as.factor(generation))) + ggplot2::labs(x=TeX("$\\sigma$"), y = "Density", color = "Generation") + ggplot2::theme_classic(base_size = 20) + ggplot2::theme(legend.position="right") + ggplot2::geom_vline(ggplot2::aes(xintercept=true_parms[,3]), color="black",
                                   linetype="dashed")
ggsave(paste0("../figures/abc_gen_post_sigma.pdf"), abc_gen_post_sigma)
```

# Appendix A

## Figure 14

```{r}
# Commercial premium linked to pure premium via a Gompertz growth curve
a <- runif(n, 5, 10) ; b <- runif(n, 2, 6) ; c <- 2
df_pp["cp_gompertz"] <- a * exp(-b*exp(-c * df_pp$pp))

# Isotonic fit of the gompertz growth curve
data <- df_pp[c("r", "d", "l")]
data["x"] <- df_pp$cp
res_iso <- isoreg(df_pp$pp, df_pp$cp_gompertz)
df_pp <- df_pp[order(df_pp$pp), ]
df_pp["cp_iso_gompertz"] <- res_iso$yf

(iso_plot <- ggplot(data = df_pp) + geom_point(mapping = aes(x= pp, y = cp_gompertz)) + geom_step(mapping = aes(x= pp, y = cp_iso_gompertz)) +  ggplot2::theme_classic(base_size = 20) + labs(x= "Pure premium", y = "Commercial premium", title = "")) 
ggsave("../figures/gompertz_iso_plot.pdf", iso_plot)

```


## Figure 15

```{r}
# Linear regression in the linear link case
res_lm_linear <- lm(df_pp$cp_linear ~ df_pp$pp)

# Linear regression in the Gompertz link case
res_lm_gompertz <- lm(df_pp$cp_gompertz ~ df_pp$pp)

# Calculation of the residuak of the linear and isotonic model
residual_df <- rbind(
  data.frame(
  residuals = res_lm_linear$residuals, 
  model = "Linear",
  link = "Linear"),
  data.frame(
  residuals = res_lm_gompertz$residuals, 
  model = "Linear",
  link = "Gompertz"),
  data.frame(
  residuals = df_pp$cp_linear - df_pp$cp_iso_linear, 
  model = "Isotonic",
  link = "Linear"), 
  data.frame(
  residuals = df_pp$cp_gompertz - df_pp$cp_iso_gompertz, 
  model = "Isotonic",
  link = "Gompertz")
  )
  
  
(residual_boxplot <- ggplot(data = residual_df) + geom_boxplot(mapping = aes(y = residuals, x = as.factor(link), color = model)) + ggplot2::theme_classic(base_size = 20) + ggplot2::theme(legend.position="right") + ggplot2::labs(x= "Link function", color = "Regression model", y = "Residuals"))

ggsave(paste0("../figures/residual_boxplot.pdf"), residual_boxplot)
```

