---
title: "Plots for section 2 of the paper entitled 'Market-based Insurance Ratemaking' "
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(latex2exp)
library(IsoPriceR)
library(ggplot2)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
getwd()
```

Let $X\sim\text{Poisson}(\lambda = 3)-\text{LogNormal}(0,1)$ be the risk. The coverage offered by insurance companies is 
$$
g(X) = \min(\max(r\cdot X - d), 0), l)
$$
Assume that $n = 100$ contract are proposed by various companies such that 
$$
r_i \sim \text{Unif}([0.5, 1])\text{, }d_i\sim\text{Unif}([0, 6])\text{, }l_i = \infty\text{, for }i = 1,\ldots, 100.
$$
```{r}
set.seed(142)
# # Loss model
freq_dist <- model("poisson", c("lambda"))
sev_dist <- model("lognormal", c("mu", "sigma"))
l_m <- loss_model(freq_dist, sev_dist, "Poisson-Lognormal")
# # True parameter
lambda_true <- 3; mu_true <- 0; sigma_true <- 1
true_parms <- t(as.matrix(c(lambda_true, mu_true, sigma_true)))
colnames(true_parms) <- l_m$parm_names
# Data
X_true <- sample_X(l_m, true_parms, R = 10000)
summary(X_true)
p_p <- pure_premium("xs", c("r", "d", "l"))
## Premium parameters
n <- 100; d <- runif(n, min = 0, max =  6); r <- runif(n, min = 0.5, max =  1)
l <- rep(Inf, n)
#l <- runif(n, min = 4, max =  30)
th_premium <- matrix(c(r, d, l), nrow = n)
pps <- compute_pure_premia(X_true, coverage_type = "xs", th_premium)
df_pp <- data.frame(r = r, d = d, l = l, pp=pps)
pp_plot <- ggplot(data = df_pp) + geom_point(mapping = aes(x= d, y = pp, size = r)) + labs(x= "d", y = "Pure premium", title = "") + ggplot2::theme_classic(base_size = 20) 
ggsave("../figures/pp_plot.pdf", pp_plot)
```

The insurance companies use the expectation principle to determine the commercial premium with 
$$
\pi_i = (1+\eta_i)p_i,
$$
where 
$$
\eta_i\sim\text{Unif}([0.5, 2]), \text{ for }i = 1, \ldots, n.
$$
```{r}
## Commercial premium based on the expectation principle
eta <- runif(n, 1.5, 3)
df_pp["cp"] <- eta * df_pp$pp
data <- df_pp[c("r", "d", "l")]
data["x"] <- df_pp$cp
(cp_plot <- ggplot(data = df_pp) + geom_point(mapping = aes(x= pp, y = cp)) + labs(x= "Pure premium", y = "Commercial premium", title = "") + ggplot2::theme_classic(base_size = 20) )
ggsave("../figures/cp_plot.pdf", cp_plot)
```
```{r}
res_iso <- isoreg(df_pp$pp, df_pp$cp)
df_pp <- df_pp[order(df_pp$pp), ]
df_pp["cp_iso"] <- res_iso$yf

(iso_plot <- ggplot(data = df_pp) + geom_point(mapping = aes(x= pp, y = cp)) + geom_step(mapping = aes(x= pp, y = cp_iso)) +  ggplot2::theme_classic(base_size = 20) + labs(x= "Pure premium", y = "Commercial premium", title = "")) 
ggsave("../figures/iso_plot.pdf", iso_plot)
```

